# Generated by Django 5.0.4 on 2024-05-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BK_BOOKING', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=8, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('seats_booked', models.CharField(max_length=200)),
                ('show_time', models.CharField(max_length=10)),
                ('show_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=180.0, max_digits=6)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BK_BOOKING.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
